FROM centos:7
MAINTAINER "Kyehwan Lee"
ENV container docker


################## BEGIN INSTALLATION ######################
RUN yum -y install epel-release
RUN yum -y install git gcc make automake wget uthash-devel libconfig libconfig-devel openssl openssl-devel libcrypto.so.* telnet less gcc net-tools

WORKDIR /root
RUN git clone https://github.com/usnistgov/NIST-BGP-SRx.git
RUN git clone https://github.com/usnistgov/gobgpsrx.git

WORKDIR /root/NIST-BGP-SRx/srx-crypto-api/
RUN ./configure --prefix=/usr CFLAGS="-O0 -g"
RUN make all install



WORKDIR /root
RUN wget https://go.dev/dl/go1.19.5.linux-amd64.tar.gz \
    && rm -rf /usr/local/go && tar -C /usr/local -xzf go1.19.5.linux-amd64.tar.gz 

ENV GOPATH /root
ENV PATH $PATH:/root/bin:/usr/local/go/bin:$GOPATH/bin


## --- gobgpsrx build & install
WORKDIR /root/gobgpsrx
RUN export CGO_CFLAGS="-I/usr/include/srx/" \
    && export CGO_LDFLAGS="-L/usr/lib64/srx/ -lSRxBGPSecOpenSSL -lSRxCryptoAPI -Wl,-rpath -Wl,/usr/lib64/srx/" \
	&& export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin \
	&& go install ./...


################## BEGIN CONFIGURATION ######################
# Use the sample configurations as our production configs
EXPOSE 179

WORKDIR /root/bin
#COPY gobgpd.conf gobgpd.conf
VOLUME ["/root/bin"]
#ENTRYPOINT ["gobgpd", "-p"]
CMD ["gobgpd", "-p", "-f", "/etc/gobgpd.conf", "--log-level=debug"]
#CMD ["sleep", "infinity"]


################
# Example usage: 
################
# docker run --rm -it -v $PWD/gobgpsrx.conf:/etc/gobgpd.conf gobgpsrx:latest gobgpd -p -f /etc/gobgpd.conf -l=debug

#  $ head -n 25 gobgpsrx.conf
# [global.config]
#	as = 65002
#	router-id = "172.17.0.2"
#	key-path = "/root/NIST-BGP-SRx/examples/bgpsec-keys/"
#
# [[neighbors]]
#	[neighbors.config]
#	  neighbor-address = "172.17.0.3"
#	  peer-as = 65003
#	  bgpsec-enable = true
#	  SKI = "45CAD0AC44F77EFAA94602E9984305215BF47DCD"
#
# [[rpki-servers]]
#	[rpki-servers.config]
#	  address = "172.37.0.4"
#	  port = 323
