#! /bin/sh -x

#+++ bridge configuration start
brctl addbr br1
brctl stp br1 off
ifconfig br1 10.1.1.1/24 up

#+++ create network namespace nodes [0]
ip netns add ns0
ip link add veth0 type veth peer name veth1
ip link set veth1 netns ns0
ip netns exec ns0 ifconfig lo up
ip netns exec ns0 ifconfig veth1 10.1.1.2/24 up
brctl addif br1 veth0
ip link set dev veth0 up

#+++ create network namespace nodes [1]
ip netns add ns1
ip link add veth2 type veth peer name veth3
ip link set veth3 netns ns1
ip netns exec ns1 ifconfig lo up
ip netns exec ns1 ifconfig veth3 10.1.1.3/24 up
brctl addif br1 veth2
ip link set dev veth2 up

sleep 1
#ip netns exec ns1 bash --rcfile <(echo "PS1=\"ns1>\"")
iptables -I INPUT 1 -p tcp --dport 179 -j ACCEPT
