apiVersion: v1
kind: PersistentVolume
metadata:
  name: srx-pv
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/mirror
    server: 192.168.10.2

