############################################################
# Dockerfile to build Quagga container images
# Based on CentOS 7
############################################################
FROM centos:latest
MAINTAINER "Kyehwan Lee" 
ENV container docker


################## BEGIN INSTALLATION ######################
# Install Quagga, Telnet, and TCPDump
RUN yum -y install quagga \
    telnet \
    tcpdump
##################### INSTALLATION END #####################

################## BEGIN CONFIGURATION ######################
# Use the sample configurations as our production configs
# COPY babeld.conf /etc/quagga/babeld.conf
VOLUME ["/test"]
#ADD bgpd.conf /test
#WORKDIR /opt/project/docker_test
#COPY bgpd.conf /etc/quagga/bgpd.conf
# COPY isisd.conf /etc/quagga/isisd.conf
# RUN mv ospf6d.conf /etc/quagga/ospf6d.conf
# RUN mv ospfd.conf /etc/quagga/ospfd.conf
# RUN mv ripd.conf /etc/quagga/ripd.conf
# RUN mv ripngd.conf /etc/quagga/ripngd.conf
# RUN mv zebra.conf /etc/quagga/zebra.conf

EXPOSE 2605 179

#CMD ["bgpd -f /test/bgpd.conf"]
