apiVersion: v1
kind: Pod
metadata:
  name: quaggasrx-pod
spec:
  containers:
  - name: quaggasrx
    image: kyehwanl/nist-bgp-srx:6
    command: ["/bin/sh", "-c"]
    args:
    - sed "s/srx connect/srx connect 172.37.0.100 17900/g" /usr/etc/bgpd.conf > /tmp/bgpd.conf;
      sed "s/verified.//g" /tmp/bgpd.conf > /etc/bgpd.conf;
      bgpd -u root -f /etc/bgpd.conf;
    volumeMounts:
    - name: bgpsec-key 
      mountPath: /usr/opt/bgp-srx-examples/bgpsec-keys 

  imagePullSecrets:
  - name: regcred

  volumes:
  - name: bgpsec-key
    hostPath: 
      path: /home/vagrant/NIST-BGP-SRx/examples/bgpsec-keys 


