apiVersion: v1
kind: Service
metadata:
  name: quaggasrx-service
  labels:
    app: quaggasrx
spec:
  clusterIP: None
  ports:
    - name: bgp-port
      port: 5179
      targetPort: 179
    - name: bgp-cli-port
      port: 52605 
      targetPort: 2605 
  selector:
    app: bgp-srx
---
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: quaggasrx-statefulset
  labels:
    app: quaggasrx
spec:
  selector:
    matchLabels:
      app: quaggasrx
  serviceName: quaggasrx-service
  template:
    metadata:
      labels:
        app: quaggasrx
    spec:
      containers:
      - name: quaggasrx
        image: kyehwanl/nist-bgp-srx:6
        command: ["/bin/sh", "-c"] 
        args:
          - sed "s/srx connect/srx connect 172.37.0.100 17900/g" /usr/etc/bgpd.conf > /tmp/bgpd.conf;
            sed "s/verified.//g" /tmp/bgpd.conf > /etc/bgpd.conf;
            bgpd -u root -f /etc/bgpd.conf;
        ports:
          - name: bgp-cli-port
            containerPort: 2605
          - name: bgp-port
            containerPort: 179
        volumeMounts:
        - name: bgpsec-key 
          mountPath: /usr/opt/bgp-srx-examples/bgpsec-keys 

      imagePullSecrets:
      - name: regcred

      volumes:
      - name: bgpsec-key
        hostPath: 
          path: /home/vagrant/NIST-BGP-SRx/examples/bgpsec-keys 



