############################################################
# Dockerfile to build srx server images
# Based on CentOS 6
############################################################
FROM centos:centos6
MAINTAINER "Kyehwan Lee" 
ENV container docker


################## BEGIN INSTALLATION ######################
# Install Quagga, Telnet, and TCPDump
RUN yum -y install wget libconfig openssl net-snmp telnet less strace
##################### INSTALLATION END #####################

################## BEGIN CONFIGURATION ######################
RUN echo "[srx]" > /etc/yum.repos.d/srx.repo
RUN echo "name = SRx" >> /etc/yum.repos.d/srx.repo
RUN echo "baseurl = http://129.6.140.211/temp/proj-bgp/srx-repo/" >> /etc/yum.repos.d/srx.repo
RUN echo "gpgcheck = 0" >> /etc/yum.repos.d/srx.repo

RUN yum repolist
RUN yum install -y srx

EXPOSE 2605 179

#COPY bgpd.conf /etc/quagga/bgpd.conf
#CMD ["bgpd", "-u", "root"]

